# 데이터셋 링크
- https://drive.google.com/file/d/15RN0lq7ouIXl5IXzMTAnCrogYPuH11fv/view?usp=sharing
- https://drive.google.com/file/d/1nZQHhBendwdhtNzXXiD9clOgXOTSdmMn/view?usp=sharing
- https://drive.google.com/file/d/10VKWGcPgREwf-l7vveegKtQf5XYqYlNA/view?usp=sharing

In [38]:
import numpy as np

## 1. MAE 와 RMSE 함수 구현하기
- 다음과 같이 실제 값과 , 모델이 예측한 값이 각각 100개가 있다.
- 실제값과 예측값 사이에 평균 오차를 구하는 함수 두개를 구현해보자.

In [39]:
np.random.seed(42)
target = np.random.randint(50, 91,100) # 정답값
pred = np.random.randint(40, 100,100) # 예측값
target , pred

(array([88, 78, 64, 57, 70, 88, 68, 72, 60, 60, 73, 85, 89, 73, 52, 71, 51,
        73, 79, 87, 51, 70, 82, 61, 71, 74, 76, 77, 65, 64, 52, 86, 56, 70,
        58, 88, 67, 53, 74, 63, 58, 75, 51, 69, 77, 56, 57, 84, 63, 66, 85,
        89, 53, 51, 55, 53, 78, 67, 75, 83, 59, 85, 63, 80, 64, 57, 63, 72,
        89, 70, 65, 67, 73, 75, 74, 90, 78, 64, 50, 74, 56, 58, 73, 50, 57,
        73, 60, 66, 57, 84, 84, 82, 54, 88, 90, 77, 56, 58, 57, 61],
       dtype=int32),
 array([73, 72, 87, 94, 62, 63, 76, 74, 83, 79, 61, 66, 74, 40, 74, 76, 86,
        53, 42, 40, 44, 65, 94, 53, 78, 66, 48, 54, 54, 65, 81, 99, 52, 90,
        71, 78, 88, 91, 71, 43, 69, 76, 62, 78, 84, 54, 82, 68, 75, 52, 71,
        46, 98, 90, 61, 67, 41, 81, 84, 96, 92, 45, 67, 67, 83, 83, 59, 69,
        50, 97, 94, 67, 64, 78, 72, 40, 96, 66, 96, 91, 52, 80, 42, 78, 45,
        47, 66, 48, 76, 72, 90, 81, 83, 63, 54, 98, 93, 71, 71, 63],
       dtype=int32))

In [40]:
len(pred)

100

### MAE(Mean Absolute Error)
- 실제 값과 예측 값의 차이를 절대값으로 변환해 평균
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [41]:
def mae(target,pred):
    return np.mean(abs(np.subtract(target,pred)))
mae(target,pred)

np.float64(17.8)

### RMSE(Root Mean Squared Error)
- 실제 값과 예측 값의 차이를 제곱한 뒤 평균한 후에 루트

$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [42]:
def rmse(target,pred):
    return (np.mean(np.square(target-pred)))**0.5

rmse(target,pred)

np.float64(21.829796151132516)

## 2.시그모이드 함수 구현하기
- S와 같은 형태로 미분 가능한 0~1 사이의 값을 반환한다.
- 이진 분류에 출력 함수로 사용된다.
$$
y = \frac{1}{1+e^{-x}}
$$

- x 변수에 있는 배열의 요소들을 시그모이드 함수에 넣어 0 ~ 1 사이 값들로 변경하시오.

In [43]:
np.random.seed(42)
x = np.random.randint(-10,10,10)
x

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7], dtype=int32)

```
아래 셀의 코드 작성하여 함수구현
```

In [44]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
sigmoid(x)

array([1.79862100e-02, 9.99876605e-01, 9.82013790e-01, 5.00000000e-01,
       4.74258732e-02, 1.79862100e-02, 9.99664650e-01, 5.00000000e-01,
       5.00000000e-01, 9.11051194e-04])

## 3.다음의 3행 2열형태의 배열에서 두개 열 위치를 바꾸시오.

In [45]:
np.random.seed(42)
arr = np.random.randint(50,100,[3,2])
arr

array([[88, 78],
       [64, 92],
       [57, 70]], dtype=int32)

```
아래 셀의 코드 작성
```

In [46]:
arr = arr[:, [1, 0]]  # 모든행 : 1,0 열 바꾸기
arr

array([[78, 88],
       [92, 64],
       [70, 57]], dtype=int32)

## 4.다음의 배열에서 각행의 평균을 구하시오.

In [47]:
np.random.seed(42)
arr = np.random.randint(50, 101, (4, 3))
arr

array([[88, 78, 64],
       [92, 57, 70],
       [88, 68, 72],
       [60, 60, 73]], dtype=int32)

In [48]:
arr.sum(axis=1)/3

array([76.66666667, 73.        , 76.        , 64.33333333])

```
아래 셀의 코드 작성
```

## 데이터 설명
- 다음은 2021년 삼성주식 데이터이다
- 시계열 학습이 가능한 형태로 변환되어있다.
- 행마다 10일치의 시작가 ,상한가 , 하한가, 종가 에 대한 행렬이 들어가 있다.

In [49]:
DATA_PATH = "data/"

In [50]:
samsung_stock_3d = np.load(f"{DATA_PATH}samsung_stock_2021_3d.npy")
samsung_stock_3d.shape

(234, 10, 4)

- 한행을 보면 2차원 행렬 형태로 되어있다.
    - 행은 일자
    - 열은 시작가,상한가,하한가,종가 순

In [51]:
samsung_stock_3d[0]  # (10, 4)

array([[81000, 84400, 80200, 83000],
       [81600, 83900, 81600, 83900],
       [83300, 84500, 82100, 82200],
       [82800, 84200, 82700, 82900],
       [83300, 90000, 83000, 88800],
       [90000, 96800, 89500, 91000],
       [90300, 91400, 87800, 90600],
       [89800, 91200, 89100, 89700],
       [88700, 90000, 88700, 89700],
       [89800, 91800, 88000, 88000]])

## 머신러닝 모델에서 학습이 가능하게 2차원 형태로 변경해보자..

## 5. samsung_stock_3d 변수의 3차원 데이터에 각 행의 행렬을 벡터 형태로 변환하여 데이터셋을 2차원형태로 변경하여 samsung_stock_2d 라는 변수에 담으세요.
- samsung_stock_2d 의 shape -> (234,40)

```
아래 셀의 코드 작성
```

In [52]:
samsung_stock_2d = samsung_stock_3d.reshape(234,40) # samsung_stock_3d.reshape(samsung_stock_3d.shape[0],-1)
samsung_stock_2d.shape

(234, 40)

## 6. samsung_stock_3d 변수의 3차원 데이터에 각 행의 시작가 ,상한가 , 하한가, 종가별로 평균을 구해 2차원 형태로 변경하여 samsung_stock_avg 라는 변수에 담으세요.
- samsung_stock_avg 의 shape -> (234,4)

```
아래 셀의 코드 작성
```

In [53]:
samsung_stock_avg = samsung_stock_3d.sum(axis=1)/2340
samsung_stock_avg.shape

(234, 4)

## 7. 5번과 6번에서 생성한 변수들의 데이터를 옆으로 합쳐서 x_train 변수에 넣어주세요.

```
아래 셀의 코드 작성
```

In [54]:
x_train = np.concatenate([samsung_stock_2d,samsung_stock_avg], axis=1)
# x_train.shape

## 8. x_train변수의 각 특성(열)들에 최대값과 최소값들을 구하시오.

```
아래 셀의 코드 작성
```

In [56]:
mins, maxs = np.quantile(x_train,[0,1])

In [19]:
x_train.min(axis=0) # 최소값
x_train.max(axis=0) # 최댓값

array([90300.        , 96800.        , 89500.        , 91000.        ,
       90300.        , 96800.        , 89500.        , 91000.        ,
       90300.        , 96800.        , 89500.        , 91000.        ,
       90300.        , 96800.        , 89500.        , 91000.        ,
       90300.        , 96800.        , 89500.        , 91000.        ,
       90300.        , 96800.        , 89500.        , 91000.        ,
       90300.        , 91800.        , 89100.        , 90600.        ,
       89800.        , 91800.        , 89100.        , 89700.        ,
       89800.        , 91800.        , 88700.        , 89700.        ,
       89800.        , 91800.        , 88000.        , 89400.        ,
         378.29059829,   386.36752137,   372.05128205,   378.24786325])

## 9.x_train변수의 각 특성(열)들에 분위수기준으로 5% 지점값들과 95% 지점값들을 구하시오

```
아래 셀의 코드 작성
```

In [ ]:
np.quantile(x_train,0.05,axis=0), np.quantile(x_train,0.95,axis=0)

## 10. 이상치를 제거해보기
- x_train변수의 특성(열)들에 분위수 기준 5% 지점의 미만값들을 5% 지점값으로 변경하고
- 95% 지점을 초과하는 값들을 95% 지점값으로 변경해보세요.

```
아래 셀의 코드 작성
```

In [21]:
np.clip(x_train, np.quantile(x_train,0.05), np.quantile(x_train,0.95))

array([[81000.        , 84400.        , 80200.        , ...,
          379.57264957,   364.4017094 ,   371.70940171],
       [81600.        , 83900.        , 81600.        , ...,
          380.81196581,   366.06837607,   372.56410256],
       [83300.        , 84500.        , 82100.        , ...,
          382.56410256,   366.92307692,   373.88888889],
       ...,
       [78300.        , 78600.        , 77100.        , ...,
          345.04273504,   345.04273504,   345.04273504],
       [77400.        , 78200.        , 77000.        , ...,
          345.04273504,   345.04273504,   345.04273504],
       [77400.        , 77600.        , 76800.        , ...,
          345.04273504,   345.04273504,   345.04273504]])

## 11.x_train 데이터셋에서 20%의 데이터의 인덱스들을 리스트에 담아 5번 랜덤하게 반환하는 제너레이터(리스트 형태로 반환 가능) 함수를 만들어주세요
- 단, 5번 랜덤하게 반환하는 과정에서 동일한 행의 인덱스가 나오면 안된다.
    - 한번 나온 행의 인덱스는 다시 나오면 안된다는 의미
    - 모든 행의 인덱스가 한번씩은 무조건 나와야한다.
- 234행 나누기 5를 할경우 나머지가 생기기 때문에 5번째 나오는 인덱스들이 담긴 리스트는 앞서 나온 크기와 차이가 나도 된다.  
- 제너레이터가 어려우신 분들은 그냥 인덱스들을 담고 있는 리스트들을 새로운 리스트에 담아서 return 하셔도 됩니다.

```
아래 셀의 코드 작성하여 함수 구현
```

* 11번은 반복문 써야함

In [ ]:
################ 제너레이터 
def split_dataset(data):
    in_dex = np.arange(len(data))
    np.random.shuffle(in_dex)
    one_five_len = int(np.ceil(len(data) * 0.2)) 
    for i in range(5):
        start = i * one_five_len
        end = (i + 1) * one_five_len
        yield in_dex[start:end]  # 인덱스 반환

gen = split_dataset(x_train)
for idx in gen:
    print(idx)

* yield from 사용한 방식

In [59]:
def split_dataset(dataset):
    n_split = 5
    n_row=len(dataset)
    index_arr = np.arange(n_row)
    n_samples = n_row//n_split
    np.random.shuffle(index_arr)
    # 나머지체크
    n_sub = n_row - n_samples *n_split
    index_list = index_arr[:n_row-n_sub].reshape(n_split,n_samples).tolist()

    if n_sub > 0 :
        index_list[-1].extend(index_arr[n_row-n_sub:])

    yield from index_list
split_dataset(x_train)

In [ ]:
np.arange(0,10).reshape(5,2)

In [23]:
# x_train.shape -- (234, 44)
# len(x_train) -- 46+47+47+47+47

-----------------------------------

- 다음 셀은 위에 함수 실행 결과를 검증하는 부분

In [24]:
index_list = split_dataset(x_train)
lst = []
for idx in index_list:
    lst.extend(idx)
np.all( np.array(sorted(lst)) == np.arange(len(x_train)) ) # True 가 나와야 성공!!

np.True_

## 12.시계열 학습데이터 만들기
- 다음의 데이터는 2021년도 삼성 주식 데이터이다.
- 열부분은 시작가 ,상한가 , 하한가, 종가 순으로 되어있다.
- 행은 2021년도 거래 일자이다.

In [25]:
samsung_stock = np.load(f"{DATA_PATH}samsung_stock_2021.npy")
samsung_stock.shape

(248, 4)

In [26]:
samsung_stock[-5:] # 뒤에 5행만 확인해보자

array([[80200, 80800, 80200, 80500],
       [80600, 80600, 79800, 80200],
       [80200, 80400, 79700, 80300],
       [80200, 80200, 78500, 78800],
       [78900, 79500, 78100, 78300]])

### 시계열 학습데이터 형태로 반환하는 함수를 만드시오.
- samsung_stock 변수의 데이터는 2차원 데이터이다.
- 학습데이터는 행별로 10일치의 행과 4열(시작가 ,상한가 , 하한가, 종가) 형태의 행렬을 담고 있는 3차원 형태의 데이터셋으로 변경하시오.
- 정답데이터는 미래의 5일치의 종가를 예측해야 한다는 가정하에 행별로 미래의 5일치의 종가가 담긴 2차원 형태의 데이터셋으로 변경하시오.
- 1일씩 이동하면서 데이터셋을 구성하시오.

```
아래 셀의 코드 작성하여 함수 구현
```

In [27]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    x_train = []
    y_train = []
    len_stock = len(samsung_stock) # 243

    for i in range(len_stock - seq_len - pred_len + 1):
        x_train.append(samsung_stock[i:i + seq_len])
        y_train.append(samsung_stock[i + seq_len :i + seq_len + pred_len,-1])
    
    return np.array(x_train), np.array(y_train)

-------------------------------------

- 다음 셀들은 위에 함수 실행 결과를 검증하는 부분

In [28]:
x_train , y_train = transform_data(samsung_stock)
x_train.shape, y_train.shape # ((234, 10, 4), (234, 5))

((234, 10, 4), (234, 5))

In [29]:
x_samsung_stock = np.load(f"{DATA_PATH}samsung_stock_2021_3d.npy")
y_samsung_stock = np.load(f"{DATA_PATH}y_train.npy")
np.all(x_samsung_stock == x_train) , np.all(y_samsung_stock == y_train) # 둘다 True 가 나와야 성공!!

(np.True_, np.True_)